export const breed_list = [{
  "id": 1,
  "name": "哈士奇",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "工作犬"
}, {
  "id": 2,
  "name": "藏獒",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$不掉毛",
  "type_func": "工作犬"
}, {
  "id": 3,
  "name": "贵宾犬",
  "type_size": "小型犬$小型",
  "type_feat": "聪明$易训$不掉毛$耐热",
  "type_func": "玩具犬$家庭犬"
}, {
  "id": 4,
  "name": "松狮",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$会看家",
  "type_func": "家庭犬"
}, {
  "id": 5,
  "name": "边境牧羊犬",
  "type_size": "中型犬$中型",
  "type_feat": "聪明$易训",
  "type_func": "牧羊犬"
}, {
  "id": 6,
  "name": "吉娃娃",
  "type_size": "超小型犬$超小型",
  "type_feat": "会看家$耐热",
  "type_func": "玩具犬"
}, {
  "id": 7,
  "name": "德国牧羊犬",
  "type_size": "大型犬$大型",
  "type_feat": "聪明$易训",
  "type_func": "牧羊犬"
}, {
  "id": 8,
  "name": "秋田犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "不爱叫$会看家",
  "type_func": "工作犬"
}, {
  "id": 9,
  "name": "蝴蝶犬",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$聪明$易训$不掉毛$耐热",
  "type_func": "玩具犬"
}, {
  "id": 10,
  "name": "博美犬",
  "type_size": "超小型犬$超小型",
  "type_feat": null,
  "type_func": "玩具犬"
}, {
  "id": 11,
  "name": "杜宾犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "聪明$易训$会看家",
  "type_func": "工作犬"
}, {
  "id": 12,
  "name": "柴犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$耐热",
  "type_func": "家庭犬"
}, {
  "id": 13,
  "name": "大丹犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "不爱叫$友善",
  "type_func": "工作犬"
}, {
  "id": 14,
  "name": "卡斯罗",
  "type_size": "大型犬$大型",
  "type_feat": "耐热",
  "type_func": "工作犬"
}, {
  "id": 15,
  "name": "法国斗牛犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "家庭犬"
}, {
  "id": 16,
  "name": "罗威纳犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$聪明$会看家",
  "type_func": "工作犬"
}, {
  "id": 17,
  "name": "英国斗牛犬",
  "type_size": "中型犬$中型",
  "type_feat": "耐热",
  "type_func": "家庭犬"
}, {
  "id": 18,
  "name": "萨摩耶犬",
  "type_size": "中型犬$中型",
  "type_feat": "友善$不掉毛",
  "type_func": "工作犬"
}, {
  "id": 19,
  "name": "阿富汗猎犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$会看家",
  "type_func": "狩猎犬"
}, {
  "id": 20,
  "name": "腊肠犬",
  "type_size": "中型犬$中型",
  "type_feat": "会看家",
  "type_func": "狩猎犬"
}, {
  "id": 21,
  "name": "巴哥犬",
  "type_size": "小型犬$小型",
  "type_feat": "不掉毛",
  "type_func": "玩具犬"
}, {
  "id": 22,
  "name": "西施犬",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "玩具犬"
}, {
  "id": 23,
  "name": "大白熊犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "不爱叫$不掉毛$会看家",
  "type_func": "工作犬"
}, {
  "id": 24,
  "name": "圣伯纳犬",
  "type_size": "大型犬$大型",
  "type_feat": "粘人$不爱叫$不掉毛",
  "type_func": "工作犬"
}, {
  "id": 25,
  "name": "金毛寻回犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$聪明$易训$友善",
  "type_func": "枪猎犬"
}, {
  "id": 26,
  "name": "法老王猎犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$不掉毛$耐热",
  "type_func": "狩猎犬"
}, {
  "id": 27,
  "name": "斗牛梗",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫",
  "type_func": "梗类犬"
}, {
  "id": 28,
  "name": "阿拉斯加雪橇犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫",
  "type_func": "工作犬"
}, {
  "id": 29,
  "name": "马尔济斯犬",
  "type_size": "超小型犬$超小型",
  "type_feat": "会看家$耐热",
  "type_func": "玩具犬"
}, {
  "id": 30,
  "name": "兰波格犬",
  "type_size": "超大型犬$超大型",
  "type_feat": null,
  "type_func": "工作犬"
}, {
  "id": 31,
  "name": "西高地白梗",
  "type_size": "小型犬$小型",
  "type_feat": "不掉毛",
  "type_func": "梗类犬"
}, {
  "id": 32,
  "name": "比利时牧羊犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$聪明$易训",
  "type_func": "牧羊犬"
}, {
  "id": 33,
  "name": "卷毛比雄犬",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$不掉毛",
  "type_func": "家庭犬"
}, {
  "id": 34,
  "name": "寻血猎犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$友善$不掉毛",
  "type_func": "狩猎犬"
}, {
  "id": 35,
  "name": "纽芬兰犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "粘人$不爱叫$友善",
  "type_func": "工作犬"
}, {
  "id": 36,
  "name": "北京犬",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "玩具犬"
}, {
  "id": 37,
  "name": "猎兔犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "狩猎犬"
}, {
  "id": 38,
  "name": "爱尔兰猎狼犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "不爱叫",
  "type_func": "狩猎犬"
}, {
  "id": 39,
  "name": "伯恩山犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫",
  "type_func": "工作犬"
}, {
  "id": 40,
  "name": "喜乐蒂牧羊犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$聪明$易训$会看家",
  "type_func": "牧羊犬"
}, {
  "id": 41,
  "name": "波尔多犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "工作犬"
}, {
  "id": 42,
  "name": "迷你杜宾",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$易训$会看家",
  "type_func": "玩具犬"
}, {
  "id": 43,
  "name": "惠比特犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫",
  "type_func": "狩猎犬"
}, {
  "id": 44,
  "name": "中国冠毛犬",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$友善",
  "type_func": "玩具犬"
}, {
  "id": 45,
  "name": "贝灵顿梗",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$不掉毛",
  "type_func": "梗类犬"
}, {
  "id": 46,
  "name": "柯利犬",
  "type_size": "大型犬$大型",
  "type_feat": "聪明$友善",
  "type_func": "牧羊犬"
}, {
  "id": 47,
  "name": "杰克罗素梗",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 48,
  "name": "哈瓦那犬",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "玩具犬"
}, {
  "id": 49,
  "name": "苏格兰梗",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫",
  "type_func": "梗类犬"
}, {
  "id": 50,
  "name": "拉布拉多寻回犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$聪明$易训$友善",
  "type_func": "枪猎犬"
}, {
  "id": 51,
  "name": "大麦町犬",
  "type_size": "中型犬$中型",
  "type_feat": "易训",
  "type_func": "家庭犬"
}, {
  "id": 52,
  "name": "美国爱斯基摩犬",
  "type_size": "中型犬$中型",
  "type_feat": "耐热",
  "type_func": "家庭犬"
}, {
  "id": 53,
  "name": "苏俄猎狼犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "友善$耐热",
  "type_func": "狩猎犬"
}, {
  "id": 54,
  "name": "万能梗",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫",
  "type_func": "梗类犬"
}, {
  "id": 55,
  "name": "波音达",
  "type_size": "超大型犬$超大型",
  "type_feat": "不爱叫$不掉毛",
  "type_func": "枪猎犬"
}, {
  "id": 56,
  "name": "刚毛猎狐梗",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 57,
  "name": "葡萄牙水犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "工作犬"
}, {
  "id": 58,
  "name": "波利犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$不掉毛",
  "type_func": "牧羊犬"
}, {
  "id": 59,
  "name": "约克夏梗",
  "type_size": "超小型犬$超小型",
  "type_feat": "不掉毛$耐热",
  "type_func": "玩具犬"
}, {
  "id": 60,
  "name": "拉萨犬",
  "type_size": "小型犬$小型",
  "type_feat": "会看家$耐热",
  "type_func": "家庭犬"
}, {
  "id": 61,
  "name": "中国沙皮犬",
  "type_size": "中型犬$中型",
  "type_feat": "粘人$会看家",
  "type_func": "家庭犬"
}, {
  "id": 62,
  "name": "卡迪根威尔士柯基犬",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "牧羊犬"
}, {
  "id": 63,
  "name": "波士顿梗",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "家庭犬"
}, {
  "id": 64,
  "name": "比格猎犬",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$友善",
  "type_func": "狩猎犬"
}, {
  "id": 65,
  "name": "英国可卡犬",
  "type_size": "中型犬$中型",
  "type_feat": "聪明$友善$不掉毛",
  "type_func": "枪猎犬"
}, {
  "id": 66,
  "name": "古代英国牧羊犬",
  "type_size": "中型犬$中型",
  "type_feat": "粘人$不爱叫$不掉毛",
  "type_func": "牧羊犬"
}, {
  "id": 67,
  "name": "小型雪纳瑞犬",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$聪明$不掉毛",
  "type_func": "梗类犬"
}, {
  "id": 68,
  "name": "巴吉度犬",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫",
  "type_func": "狩猎犬"
}, {
  "id": 69,
  "name": "美国可卡犬",
  "type_size": "小型犬$小型",
  "type_feat": "聪明$友善$不掉毛",
  "type_func": "枪猎犬"
}, {
  "id": 70,
  "name": "西藏猎犬",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$会看家",
  "type_func": "家庭犬"
}, {
  "id": 71,
  "name": "马士提夫獒犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "不爱叫",
  "type_func": "工作犬"
}, {
  "id": 72,
  "name": "斗牛獒犬",
  "type_size": "大型犬$大型",
  "type_feat": "会看家",
  "type_func": "工作犬"
}, {
  "id": 73,
  "name": "凯利蓝梗",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$不掉毛",
  "type_func": "梗类犬"
}, {
  "id": 74,
  "name": "法国狼犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "牧羊犬"
}, {
  "id": 75,
  "name": "澳大利亚牧羊犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫",
  "type_func": "牧羊犬"
}, {
  "id": 76,
  "name": "彭布罗克威尔士柯基犬",
  "type_size": "小型犬$小型",
  "type_feat": "聪明",
  "type_func": "牧羊犬"
}, {
  "id": 77,
  "name": "英国猎狐犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫",
  "type_func": "狩猎犬"
}, {
  "id": 78,
  "name": "丝毛梗",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$不掉毛$耐热",
  "type_func": "玩具犬"
}, {
  "id": 79,
  "name": "匈牙利牧羊犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$会看家",
  "type_func": "工作犬"
}, {
  "id": 80,
  "name": "拳狮犬",
  "type_size": "大型犬$大型",
  "type_feat": "不掉毛",
  "type_func": "工作犬"
}, {
  "id": 81,
  "name": "山地犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "牧羊犬"
}, {
  "id": 82,
  "name": "西藏梗",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫",
  "type_func": "家庭犬"
}, {
  "id": 83,
  "name": "罗得西亚脊背犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$会看家",
  "type_func": "狩猎犬"
}, {
  "id": 84,
  "name": "湖畔梗",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$会看家",
  "type_func": "梗类犬"
}, {
  "id": 85,
  "name": "爱尔兰雪达犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "枪猎犬"
}, {
  "id": 86,
  "name": "瑞典柯基犬",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "牧羊犬"
}, {
  "id": 87,
  "name": "芬兰拉普猎犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "牧羊犬"
}, {
  "id": 88,
  "name": "德国宾莎犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "工作犬"
}, {
  "id": 89,
  "name": "库瓦兹犬",
  "type_size": "超大型犬$超大型",
  "type_feat": null,
  "type_func": "工作犬"
}, {
  "id": 90,
  "name": "奇努克犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "工作犬"
}, {
  "id": 91,
  "name": "巨型雪纳瑞犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$会看家",
  "type_func": "工作犬"
}, {
  "id": 92,
  "name": "萨路基猎犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "不爱叫$不掉毛$会看家",
  "type_func": "狩猎犬"
}, {
  "id": 93,
  "name": "维希拉猎犬",
  "type_size": "大型犬$大型",
  "type_feat": "耐热",
  "type_func": "枪猎犬"
}, {
  "id": 94,
  "name": "澳大利亚牧牛犬",
  "type_size": "中型犬$中型",
  "type_feat": "聪明$易训",
  "type_func": "牧羊犬"
}, {
  "id": 95,
  "name": "威尔士梗",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 96,
  "name": "格雷伊猎犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "不掉毛",
  "type_func": "狩猎犬"
}, {
  "id": 97,
  "name": "普罗特猎犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "狩猎犬"
}, {
  "id": 98,
  "name": "墨西哥无毛犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "家庭犬"
}, {
  "id": 99,
  "name": "小型斗牛梗",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫",
  "type_func": "梗类犬"
}, {
  "id": 100,
  "name": "短毛猎狐梗",
  "type_size": "小型犬$小型",
  "type_feat": "不掉毛",
  "type_func": "梗类犬"
}, {
  "id": 101,
  "name": "斯塔福郡斗牛梗",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$不掉毛",
  "type_func": "梗类犬"
}, {
  "id": 102,
  "name": "意大利灰狗",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫",
  "type_func": "玩具犬"
}, {
  "id": 103,
  "name": "威玛犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "枪猎犬"
}, {
  "id": 104,
  "name": "荷兰毛狮犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$聪明$会看家",
  "type_func": "家庭犬"
}, {
  "id": 105,
  "name": "爱尔兰水猎犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫",
  "type_func": "枪猎犬"
}, {
  "id": 106,
  "name": "美国猎狐犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫",
  "type_func": "狩猎犬"
}, {
  "id": 107,
  "name": "安纳托利亚牧羊犬",
  "type_size": "超大型犬$超大型",
  "type_feat": null,
  "type_func": "工作犬"
}, {
  "id": 108,
  "name": "冰岛牧羊犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "牧羊犬"
}, {
  "id": 109,
  "name": "帕尔森罗塞尔梗",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 110,
  "name": "英国跳猎犬",
  "type_size": "中型犬$中型",
  "type_feat": "聪明$易训",
  "type_func": "枪猎犬"
}, {
  "id": 111,
  "name": "短脚长身梗",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 112,
  "name": "爱尔兰梗",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$会看家",
  "type_func": "梗类犬"
}, {
  "id": 113,
  "name": "挪威伦德猎犬",
  "type_size": "超大型犬$超大型",
  "type_feat": null,
  "type_func": "家庭犬"
}, {
  "id": 114,
  "name": "挪威猎鹿犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "狩猎犬"
}, {
  "id": 115,
  "name": "西帕基犬",
  "type_size": "小型犬$小型",
  "type_feat": "聪明",
  "type_func": "家庭犬"
}, {
  "id": 116,
  "name": "黑俄罗斯梗",
  "type_size": "超大型犬$超大型",
  "type_feat": null,
  "type_func": "工作犬"
}, {
  "id": 117,
  "name": "苏格兰猎鹿犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "会看家",
  "type_func": "狩猎犬"
}, {
  "id": 118,
  "name": "波兰低地牧羊犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫",
  "type_func": "牧羊犬"
}, {
  "id": 119,
  "name": "挪威梗",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫",
  "type_func": "梗类犬"
}, {
  "id": 120,
  "name": "爱尔兰红白雪达犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "枪猎犬"
}, {
  "id": 121,
  "name": "大瑞士山地犬",
  "type_size": "超大型犬$超大型",
  "type_feat": "不掉毛",
  "type_func": "工作犬"
}, {
  "id": 122,
  "name": "罗秦犬",
  "type_size": "小型犬$小型",
  "type_feat": "粘人$会看家",
  "type_func": "家庭犬"
}, {
  "id": 123,
  "name": "那不勒斯獒",
  "type_size": "超大型犬$超大型",
  "type_feat": null,
  "type_func": "工作犬"
}, {
  "id": 124,
  "name": "捷克梗",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 125,
  "name": "比利时马林诺斯犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "牧羊犬"
}, {
  "id": 126,
  "name": "标准型雪纳瑞犬",
  "type_size": "中型犬$中型",
  "type_feat": "聪明",
  "type_func": "工作犬"
}, {
  "id": 127,
  "name": "德国短毛波音达",
  "type_size": "大型犬$大型",
  "type_feat": "聪明",
  "type_func": "枪猎犬"
}, {
  "id": 128,
  "name": "锡利哈姆梗",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫",
  "type_func": "梗类犬"
}, {
  "id": 129,
  "name": "红骨猎浣熊犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "狩猎犬"
}, {
  "id": 130,
  "name": "巴仙吉犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫",
  "type_func": "狩猎犬"
}, {
  "id": 131,
  "name": "戈登雪达犬",
  "type_size": "大型犬$大型",
  "type_feat": "不掉毛",
  "type_func": "枪猎犬"
}, {
  "id": 132,
  "name": "诺福克梗",
  "type_size": "小型犬$小型",
  "type_feat": "友善$不掉毛$会看家",
  "type_func": "梗类犬"
}, {
  "id": 133,
  "name": "小型葡萄牙波登可犬",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "狩猎犬"
}, {
  "id": 134,
  "name": "骑士查理王小猎犬",
  "type_size": "小型犬$小型",
  "type_feat": "友善",
  "type_func": "玩具犬"
}, {
  "id": 135,
  "name": "美国斯塔福郡梗",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 136,
  "name": "粗毛柯利犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "牧羊犬"
}, {
  "id": 137,
  "name": "切萨皮克海湾寻回犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$易训$友善$耐热",
  "type_func": "枪猎犬"
}, {
  "id": 138,
  "name": "比利时特伏丹犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$聪明$易训",
  "type_func": "牧羊犬"
}, {
  "id": 139,
  "name": "玩具猎狐梗",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 140,
  "name": "日本忡",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫",
  "type_func": "玩具犬"
}, {
  "id": 141,
  "name": "玩具曼彻斯特犬",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$会看家$耐热",
  "type_func": "玩具犬"
}, {
  "id": 142,
  "name": "爱尔兰峡谷梗",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 143,
  "name": "澳大利亚梗",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$耐热",
  "type_func": "梗类犬"
}, {
  "id": 144,
  "name": "芬兰波美拉尼亚丝毛狗",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "家庭犬"
}, {
  "id": 145,
  "name": "猎水獭犬",
  "type_size": "大型犬$大型",
  "type_feat": "粘人$友善",
  "type_func": "狩猎犬"
}, {
  "id": 146,
  "name": "挪威布哈德犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "牧羊犬"
}, {
  "id": 147,
  "name": "爱尔兰软毛梗",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 148,
  "name": "卷毛寻回犬",
  "type_size": "大型犬$大型",
  "type_feat": "易训$友善",
  "type_func": "枪猎犬"
}, {
  "id": 149,
  "name": "弗莱特寻回犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$聪明$易训",
  "type_func": "枪猎犬"
}, {
  "id": 150,
  "name": "英国玩具犬",
  "type_size": "小型犬$小型",
  "type_feat": null,
  "type_func": "玩具犬"
}, {
  "id": 151,
  "name": "迦南犬",
  "type_size": "大型犬$大型",
  "type_feat": "粘人$会看家",
  "type_func": "牧羊犬"
}, {
  "id": 152,
  "name": "弗莱特寻回犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$聪明$易训",
  "type_func": "枪猎犬"
}, {
  "id": 153,
  "name": "黑褐猎浣熊犬",
  "type_size": "大型犬$大型",
  "type_feat": "会看家",
  "type_func": "狩猎犬"
}, {
  "id": 154,
  "name": "布雷猎犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫$会看家",
  "type_func": "牧羊犬"
}, {
  "id": 155,
  "name": "布鲁塞尔格里芬犬",
  "type_size": "小型犬$小型",
  "type_feat": "粘人",
  "type_func": "玩具犬"
}, {
  "id": 156,
  "name": "德国硬毛波音达",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫",
  "type_func": "枪猎犬"
}, {
  "id": 157,
  "name": "布列塔尼犬",
  "type_size": "中型犬$中型",
  "type_feat": "聪明$友善",
  "type_func": "枪猎犬"
}, {
  "id": 158,
  "name": "美国水猎犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫",
  "type_func": "枪猎犬"
}, {
  "id": 159,
  "name": "西班牙小猎犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫",
  "type_func": "枪猎犬"
}, {
  "id": 160,
  "name": "比利牛斯牧羊犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "牧羊犬"
}, {
  "id": 161,
  "name": "树丛浣熊猎犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "狩猎犬"
}, {
  "id": 162,
  "name": "波兰德斯布比野犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫",
  "type_func": "牧羊犬"
}, {
  "id": 163,
  "name": "史毕诺犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "枪猎犬"
}, {
  "id": 164,
  "name": "美国英国猎浣熊犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "狩猎犬"
}, {
  "id": 165,
  "name": "伊比赞猎犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "狩猎犬"
}, {
  "id": 166,
  "name": "凯斯梗",
  "type_size": "超大型犬$超大型",
  "type_feat": "不爱叫",
  "type_func": "梗类犬"
}, {
  "id": 167,
  "name": "布鲁克浣熊猎犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "狩猎犬"
}, {
  "id": 168,
  "name": "迷你贝吉格里芬凡丁犬",
  "type_size": "小型犬$小型",
  "type_feat": "粘人$友善$不掉毛",
  "type_func": "狩猎犬"
}, {
  "id": 169,
  "name": "新斯科舍猎鸭寻猎犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "枪猎犬"
}, {
  "id": 170,
  "name": "捕鼠梗",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "梗类犬"
}, {
  "id": 171,
  "name": "威尔士跳猎犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫",
  "type_func": "枪猎犬"
}, {
  "id": 172,
  "name": "田野小猎犬",
  "type_size": "中型犬$中型",
  "type_feat": "不爱叫$不掉毛",
  "type_func": "枪猎犬"
}, {
  "id": 173,
  "name": "英格兰雪达犬",
  "type_size": "大型犬$大型",
  "type_feat": null,
  "type_func": "枪猎犬"
}, {
  "id": 174,
  "name": "博得猎狐犬",
  "type_size": "小型犬$小型",
  "type_feat": "不爱叫$不掉毛",
  "type_func": "梗类犬"
}, {
  "id": 175,
  "name": "苏塞克斯猎犬",
  "type_size": "小型犬$小型",
  "type_feat": "易训",
  "type_func": "枪猎犬"
}, {
  "id": 176,
  "name": "博伊金猎犬",
  "type_size": "中型犬$中型",
  "type_feat": null,
  "type_func": "枪猎犬"
}, {
  "id": 177,
  "name": "硬毛指示格里芬犬",
  "type_size": "大型犬$大型",
  "type_feat": "不爱叫",
  "type_func": "枪猎犬"
}]